### ISSUE TITLE
not build on latest LDC2

### ISSUE THREAD

**Issue by kassane** [KitsunebiGames/tinyd-rt#1]
**ldc version:** latest-CI
**project testing:** [sokol-d](http://sokol-d.dub.pm/) for wasm32 target

- **dub config:**
```sdl
subPackage {
	name "clear"
	targetType "executable"
	targetPath "build"
	dependency "tinyd-rt" version="~>0.1.1"
	dflags "-preview=all"
	lflags "-w" "-lObjC" "-all_load" "-framework" "Cocoa" "-framework" "QuartzCore" "-framework" "Foundation" "-framework" "MetalKit" "-framework" "Metal" "-framework" "AudioToolbox" platform="osx"
	lflags "-Lzig-out/lib" platform="posix"
	lflags "/LIBPATH:zig-out/lib" platform="windows"
	libs "sokol"
	libs "X11" "Xcursor" "Xi" "GL" "asound" platform="linux"
	libs "user32" "gdi32" "kernel32" "dxgi" "d3d11" "ole32" platform="windows"
	sourceFiles "src/examples/clear.d"
	excludedSourceFiles "src/examples/sgl_context.d" "src/examples/triangle.d" "src/examples/sgl_points.d" "src/examples/saudio.d" "src/examples/debugtext.d" "src/examples/mrt.d" "src/examples/user_data.d" "src/examples/cube.d" "src/examples/blend.d" "src/shaders/*.d"
	preBuildCommands "zig build -Doptimize=ReleaseFast -Dartifact"
}
```
<details>
<summary>output</summary>

```bash
 $ dub build -b release :clear
    Starting Performing "release" build using ldc2 for x86_64.
    Building tinyd-rt 0.1.1: building configuration [default]
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(197,5): Error: `__va_list_tag` is not defined, perhaps `import core.stdc.stdarg;` ?
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(197,5): Error: `pragma(printf)` function `vfprintf` must have signature `int vfprintf([parameters...], const(char)*, va_list)`
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(201,5): Error: `pragma(scanf)` function `vfscanf` must have signature `int vfscanf([parameters...], const(char)*, va_list)`
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(205,5): Error: `pragma(printf)` function `vsprintf` must have signature `int vsprintf([parameters...], const(char)*, va_list)`
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(209,5): Error: `pragma(scanf)` function `vsscanf` must have signature `int vsscanf([parameters...], const(char)*, va_list)`
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(213,5): Error: `pragma(printf)` function `vprintf` must have signature `int vprintf([parameters...], const(char)*, va_list)`
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(217,5): Error: `pragma(scanf)` function `vscanf` must have signature `int vscanf([parameters...], const(char)*, va_list)`
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(291,5): Error: `pragma(printf)` function `_vsnprintf` must have signature `int _vsnprintf([parameters...], const(char)*, va_list)`
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/core/stdc/stdio.d(294,6): Error: `pragma(printf)` function `vsnprintf` must have signature `int vsnprintf([parameters...], const(char)*, va_list)`
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/object.d(690,17): Deprecation: using `in` parameters with `extern(C)` functions is deprecated
../.dub/packages/tinyd-rt/0.1.1/tinyd-rt/source/object.d(690,17):        parameter `_ti` declared as `in` here
Error ldc2 failed with exit code 1.
```
</details>

for wasm32-target:
<details>
<summary>output</summary>

```bash
$ zig build run-clear -Dtarget=wasm32-emscripten-none -Doptimize=ReleaseFast
/home/kassane/.cache/zig/p/1220e716c111573a5d3afedfd6e54d059ae737ba19210da29eb0e864ee0fd28b1716/source/object.d(690,17): Error: cannot use `in` parameters with `extern(C)` functions
/home/kassane/.cache/zig/p/1220e716c111573a5d3afedfd6e54d059ae737ba19210da29eb0e864ee0fd28b1716/source/object.d(690,17):        parameter `_ti` declared as `in` here
```
</details>

cc: @LunaTheFoxgirl

**Comment by LunaTheFoxgirl** [comment]
WASM support is currently incomplete, but will be improved soon.

Will update on the state of WASM support as I get there.

**Comment by kassane** [comment]
Which ldc2 version was tested?

I will try to create a static library of this runtime.

I'm using the latest ldc2 version because the new target `wasm32-unknown-emscripten` was not listed `-mtriple=` in 1.35.0...1.38.0.

Maybe it will help to clarify the tested version of the current state of this tinyd.

---

Works in version 1.36.0!!

#### Reference
- https://github.com/ldc-developers/ldc/issues/4670

**Comment by LunaTheFoxgirl** [comment]
cc @kassane This repo is now outdated, new runtime lives in nurt, using numem.
Not released on dub yet, but if you clone both nurt and numem, you can enable the wasm hookset and get walloc based malloc, free, realloc, nogc_new and the like. (yay D classes!)

https://github.com/Inochi2D/nurt
